# Generated by Django 5.1.2 on 2024-12-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_adicional', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
            options={
                'db_table': 'Tamaño',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.ManyToManyField(blank=True, related_name='productos', to='panaderia.tamaño'),
        ),
    ]
