# Generated by Django 5.1.2 on 2024-11-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0004_alter_cliente_rut_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
