# Generated by Django 5.1.2 on 2024-12-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0006_alter_detallepedido_ingredientes_adicionales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='ingredientes_adicionales',
            new_name='ingredientes',
        ),
    ]
